### ISSUE TITLE
World Rescue Organization 

### ISSUE THREAD

**Issue by LORDWORLD10** [ietf-wg-add/wg-materials#3]
import Foundation

let parameters = [
  "roadmap_id": 1,
  "name": "Find map to Monkey Island",
  "description": "Or is it a recipe?"
] as [String : Any?]

let postData = try JSONSerialization.data(withJSONObject: parameters, options: [])

let url = URL(string: "https://app.productplan.com/api/v2/bars")!
var request = URLRequest(url: url)
request.httpMethod = "POST"
request.timeoutInterval = 10
request.allHTTPHeaderFields = [
  "accept": "application/json",
  "content-type": "application/json"
]
request.httpBody = postData

let (data, _) = try await URLSession.shared.data(for: request)
print(String(decoding: data, as: UTF8.self))

**Comment by vttale** [comment]
This is not an issue that is relevant to the materials of the IETF add wg.

**Comment by LORDWORLD10** [comment]
A ktorý odporúčate ?

Dňa ut, 8. okt 2024, 4:10 David C Lawrence ***@***.***>
napísal(a):

**Comment by vttale** [comment]
Nemám žiadne odporúčanie. Toto úložisko je určené pre dokumenty súvisiace s pracovnou skupinou IETF „Adaptive DNS Discovery“. Neviem, ktoré fórum je vhodnejšie na to, čo sa snažíte nastoliť.

(Preložil translate.google.com; ospravedlňujeme sa za slabú gramatiku.)

**Comment by LORDWORLD10** [comment]
Ad Info: World Rescue Organization

Network: FACEBOOK_NATIVE_BIDDING
Adapter Version: 6.17.0.0
Format: NATIVE
Ad Unit ID: 7ec8035513c30c97
Placement: native_cache_placement
Network Placement: 1434013866944721_1956541588025277
Serve ID: 9d4815af9a4726fb253f47e26fbf1e416a2432ed
Creative ID: 8861496691313477196
Ad Review Creative ID: None
Ad Domain: None
DSP Name: None
DSP ID: None
Server Parameters: Bundle[{amount=0,
placement_ids=[1434013866944721_1956541588025277], is_native=true,
encrypted_cpm=ARGLYVvhFgfX4JTmSFAgEm9S5dtGebXyF0xP_w8iV6MI2mYzst_MKJo2VUCI7ZSvQncT-jL2gkAYNyd-Y7jE5oUCGqCSOelrVtVIX-nMABE,
is_muted=true, currency=, placement_id=1434013866944721_1956541588025277}]
Muted: true
Epoch Timestamp (ms): 1730657140172

Debug Info:

Platform: Android
AppLovin SDK Version: 12.6.0
Plugin Version:
App Package Name: com.dubox.drive
Device: HONOR ALI-NX1 (HNALI-Q)
OS Version: 14
AppLovin Random Token: 6ab8bfb9-1247-4219-bed2-8d34a29c2d0c
Ad Review Version:
User ID: 4398796914608
MD:
FSIp/BIVABUAFQAAFQAVABUCABUAFQAVBAAVABUAFQYAFQAVABUIABWeDxWcKBUKABUAFQAVDAAVABUAFQ4AFQAVABUQABUAFQAVEgAVABUAFRQAFQAVABUWABUAFQAVGAAVABUAFRoAFQAVABUcABWiDhWyJRUeABUAFQAVIAAVABUAFSIAGwJcChWeDxWcKBUKAB4Vog4VsiUVHgAA

Bid Response:

{"type":"ID","bid_id":"8861496691313477196","placement_id":"1434013866944721_1956541588025277","resolved_placement_id":"1434013866944721_1956541588025277","sdk_version":"6.17.0","device_id":null,"template":200,"payload":null,"bid_time_token":"V1_eyJwbGF0Zm9ybV9pZCI6NDA2NzczNjA2NTQ3OTUxLCJvcnRiX2F1Y3Rpb25faWQiOiI5ZDQ4MTVhZjlhNDcyNmZiMjUzZjQ3ZTI2ZmJmMWU0MTZhMjQzMmVkIiwiYmlkX3NvdXJjZSI6NSwiY2x1c3Rlcl9pZCI6OSwiZW5jcnlwdGVkX2NwbSI6IkFSR0xZVnZoRmdmWDRKVG1TRkFnRW05UzVkdEdlYlh5RjB4UF93OGlWNk1JMm1ZenN0X01LSm8yVlVDSTdaU3ZRbmNULWpMMmdrQVlOeWQtWTdqRTVvVUNHcUNTT2VsclZ0VklYLW5NQUJFIiwiZGVsaXZlcnlfdHlwZSI6MCwiYmlkX3JlcXVlc3RfcHVzaF9waGFzZSI6IkMzIn0=","encrypted_cpm":"ARGLYVvhFgfX4JTmSFAgEm9S5dtGebXyF0xP_w8iV6MI2mYzst_MKJo2VUCI7ZSvQncT-jL2gkAYNyd-Y7jE5oUCGqCSOelrVtVIX-nMABE"}
